# Generated by Django 4.1 on 2025-04-08 07:15

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="team",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="team",
            name="goal_description",
        ),
        migrations.RemoveField(
            model_name="team",
            name="id",
        ),
        migrations.AddField(
            model_name="team",
            name="_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                default="a6bab9fe-28c3-4315-8ab5-2131f5bb0291",
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.DeleteModel(
            name="FitnessActivity",
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="octofit_tracker.user"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="octofit_tracker.user"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=djongo.models.fields.ArrayReferenceField(
                default=[],
                on_delete=django.db.models.deletion.CASCADE,
                to="octofit_tracker.user",
            ),
            preserve_default=False,
        ),
    ]
