# Generated by Django 4.1 on 2025-04-08 07:24

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_activity_leaderboard_user_workout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True,
                default=bson.objectid.ObjectId,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=djongo.models.fields.JSONField(default=list, null=True),
        ),
    ]
